language: cpp
compiler:
  - clang
# - gcc
# before_install:
#   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#   - sudo apt-get update -qq
#   - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.7; fi
#   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
before_script:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libboost1.54-all-dev
  - export MPIEXEC='mpiexec -launcher fork'
before_install:
  - "sudo apt-get remove openmpi-bin openmpi-common openmpi-doc -y && echo '@> '`which mpiexec`"
  
  - sudo apt-get install -q gfortran libcr0 default-jdk
  - wget -q http://www.cebacad.net/files/mpich/ubuntu/mpich-3.1/mpich_3.1-1ubuntu_amd64.deb;
  - sudo dpkg -i ./mpich_3.1-1ubuntu_amd64.deb
  - rm -f ./mpich_3.1-1ubuntu_amd64.deb
  # - wget http://www.cebacad.net/files/mpich/ubuntu/mpich-3.1/mpich_3.1-1ubuntu_amd64.deb
  # - sudo dpkg -i mpich_3.1-1ubuntu_amd64.deb || true
  # - sudo apt-get -f install -y
script:
  - "./configure && cd build/Make+Release && make -j1 VERBOSE=1 check-all-pass"
branches:
  only:
    - master
notifications:
  irc:
    channels: "chat.freenode.net#grappa.io"
    on_success: change
    on_failure: always
  email:
    - grappa-dev@cs.washington.edu
